# Air configuration for backend
# Docs: https://github.com/cosmtrek/air

root = "."           # Project root (backend)
tmp_dir = "tmp"      # Temporary build output

[build]
  #cmd = "go build -o tmp/main ./cmd/api"
  #bin = "tmp/main"
  cmd = "go build -o tmp/main.exe ./cmd/api"
  bin = "tmp/main.exe"

  include_ext = ["go", "env"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  delay = 1000         # ms
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[log]
  time = true
  color = "auto"

[debug]
  enable = false
